
head-items:
  - chainmail_helmet
  - diamond_helmet
  - golden_helmet
  - iron_helmet
  - leather_helmet
  - turtle_helmet
  - dragon_head
  - creeper_head
  - player_head
  - zombie_head
  - wither_skeleton_skull
  - carved_pumpkin
